### ISSUE TITLE
Need Help with Maintenance?

### ISSUE THREAD

**Issue by sbrandtb** [ktosiek/pytest-freezegun#19]
It seems to be used by some people, yet pull requests are stuck since half a year.

@ktosiek what's the status? Need any help?

**Comment by ktosiek** [comment]
I'm going through the issues and PRs today, and I hope to make a release this week (maybe even this evening, but let's not get our hopes too high :-)). I'm not ready to transfer maintenance just yet, but any help with triaging issues and PRs is welcome - something like what @dimaqq did on #20 is both helpful and motivating.

If it turns out I can't keep myself working on this project then I'll look for new maintainers, or a transfer to the pytest-dev organization.

**Comment by thijskramer** [comment]
@ktosiek I'd like to quote @sbrandtb:

> It seems to be used by some people, yet pull requests are stuck since half a year.
> 
> @ktosiek what's the status? Need any help?

I'm happy to help!

**Comment by wimglenn** [comment]
Hey @ktosiek, pytest-dev org member here. First thank you for making this really useful plugin :) 
Any further thoughts on transferring to pytest-dev organization for maintenance? Currently everyone on Python 3.10+ is getting deprecation warnings from the plugin

**Comment by agronholm** [comment]
> If it turns out I can't keep myself working on this project then I'll look for new maintainers, or a transfer to the pytest-dev organization.

@ktosiek Just another ping – transferring this project would really help it get updated!

**Comment by kennylajara** [comment]
@ktosiek Please consider the idea of @wimglenn 
It would be in good hands. It's probably the best idea if you don't want to see your project die and you don't have time to maintain it.

**Comment by wimglenn** [comment]
I have contacted again Tomasz from the email on his github landing page, but did not get any response after some time. I hope he is OK  :-\ 

To move forward from these deprecations I decided to simply rewrite instead of fork, since the plugin code was so short and simple. A drop-in replacement is now on PyPI as [pytest-freezer](https://pypi.org/project/pytest-freezer) and the source repo is https://github.com/wimglenn/pytest-freezer.

**Comment by BjoernPetersen** [comment]
Thanks for taking over @wimglenn! Is there a chance to move the new project into the pytest-dev organization? Just to avoid a similar situation in the future.

Edit: I'm not trying to insinuate that you won't maintain the project! Just thinking of the bus factor.

**Comment by wimglenn** [comment]
Yes, good point, I've transferred it to https://github.com/pytest-dev/pytest-freezer. The old URL should redirect.

**Comment by mgorny** [comment]
> To move forward from these deprecations I decided to simply rewrite instead of fork, since the plugin code was so short and simple. A drop-in replacement is now on PyPI as [pytest-freezer](https://pypi.org/project/pytest-freezer) and the source repo is https://github.com/wimglenn/pytest-freezer.

Honestly, I'd have preferred if you actually forked it and requested transfer of PyPI. It will take years before the few projects needing it migrate, not to mention all the hassle of "but pytest-freezegun works for me, why do you bother me!"

**Comment by merwok** [comment]
If a project is using pytest-freezegun without issue, what’s the problem then?
When they encounter problem with pytest deprecation messages or packaging issues, then they’ll have a reason to switch.

**Comment by mgorny** [comment]
The problem is that Linux distributions will have to maintain two redundant packages for a prolonged period of time, and we already have to patch pytest-freezegun.

**Comment by agronholm** [comment]
Hard to do anything about that when the original author isn't responding.

**Comment by mgorny** [comment]
Isn't that why PyPI has a process for reclaiming packages?

**Comment by agronholm** [comment]
Ah, quite right. And this project does in fact meet the requirements outlined in PEP 541.
