### ISSUE TITLE
Missing dependency on python-dateutil>=2.7.0

### ISSUE THREAD

**Issue by jdevera** [ktosiek/pytest-freezegun#25]
Perhaps this is counting on `freezegun` to depend on the right version, but I found that I had an older version that satisfied `freezegun` requirements but still failed here:

```
   File "/usr/local/lib/python2.7/dist-packages/freezegun/api.py", line 26, in <module>
     _EPOCHTZ = datetime.datetime(1970, 1, 1, tzinfo=dateutil.tz.UTC)
 AttributeError: 'module' object has no attribute 'UTC'
```

That `dateutil.tz.UTC` attribute was added in version 2.7.0 of `python-dateutil`. Seems like `pytest-freezegun` should have it as a dependency.

**Comment by ktosiek** [comment]
pytest-freezegun doesn't depend on dateutil. This issue was reported to freezegun here: https://github.com/spulec/freezegun/issues/333, and seems to be fixed in freezegun master: https://github.com/spulec/freezegun/commit/f64281d4a0b5e7ec4c870eed8ebcbb3c6ad50305.

Unfortunately it's not released yet. I think the problem was introduced in freezegun 0.3.15. You can either downgrade to 0.3.14, or add the python-dateutil dependency to your app - at least until freezegun releases 0.3.16.
